let START_TIME = Date.now();

export const games_start = [
  {
    id: "a",
    home_team: "Mexico",
    away_team: "Canada",
    home_score: 0,
    away_score: 0,
    finished: false,
    start_time: START_TIME,
  },
  {
    id: "b",
    home_team: "Spain",
    away_team: "Brazil",
    home_score: 0,
    away_score: 0,
    finished: false,
    start_time: START_TIME,
  },
  {
    id: "c",
    home_team: "Germany",
    away_team: "France",
    home_score: 0,
    away_score: 0,
    finished: false,
    start_time: START_TIME + 10,
  },
  {
    id: "d",
    home_team: "Uruguay",
    away_team: "Italy",
    home_score: 0,
    away_score: 0,
    finished: false,
    start_time: START_TIME + 10,
  },
  {
    id: "e",
    home_team: "Argentina",
    away_team: "Australia",
    home_score: 0,
    away_score: 0,
    finished: false,
    start_time: START_TIME + 20,
  },
];

export const games_update = [
  {
    id: "a",
    home_team: "Mexico",
    away_team: "Canada",
    home_score: 0,
    away_score: 5,
    finished: false,
    start_time: START_TIME,
  },
  {
    id: "b",
    home_team: "Spain",
    away_team: "Brazil",
    home_score: 10,
    away_score: 2,
    finished: false,
    start_time: START_TIME,
  },
  {
    id: "c",
    home_team: "Germany",
    away_team: "France",
    home_score: 2,
    away_score: 2,
    finished: false,
    start_time: START_TIME + 10,
  },
  {
    id: "d",
    home_team: "Uruguay",
    away_team: "Italy",
    home_score: 6,
    away_score: 6,
    finished: false,
    start_time: START_TIME + 10,
  },
  {
    id: "e",
    home_team: "Argentina",
    away_team: "Australia",
    home_score: 3,
    away_score: 1,
    finished: false,
    start_time: START_TIME + 20,
  },
];

export const games_end = [
  {
    id: "a",
    home_team: "Mexico",
    away_team: "Canada",
    home_score: 0,
    away_score: 5,
    finished: true,
    start_time: START_TIME,
  },
  {
    id: "b",
    home_team: "Spain",
    away_team: "Brazil",
    home_score: 10,
    away_score: 2,
    finished: false,
    start_time: START_TIME,
  },
  {
    id: "c",
    home_team: "Germany",
    away_team: "France",
    home_score: 2,
    away_score: 2,
    finished: true,
    start_time: START_TIME + 10,
  },
  {
    id: "d",
    home_team: "Uruguay",
    away_team: "Italy",
    home_score: 6,
    away_score: 6,
    finished: false,
    start_time: START_TIME + 10,
  },
  {
    id: "e",
    home_team: "Argentina",
    away_team: "Australia",
    home_score: 3,
    away_score: 1,
    finished: false,
    start_time: START_TIME + 20,
  },
];
